# Color of bottom bar
set -g status-bg "#f38ba8"
# Mouse support
set -g mouse on
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
# Border colors (same color for active and inactive borders)
set -g pane-border-style "fg=#94e2d5"
set -g pane-active-border-style "fg=#94e2d5"
# So that colors in Neovim are displayed correctly
set-option -sa terminal-overrides ",xterm*:Tc"
# Use Vim-style hjkl to switch panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
