format = """
$hostname\
$directory\
$git_branch\
$fill\
$cmd_duration\
$line_break\
$python\
$character
"""

[hostname]
ssh_only = false
style = "bold #FF55FF"

[git_branch]
style = "bold #ef9f76"

[directory]
style = "bold #55ffff"

[python]
symbol = "Python "
format = '[(\($virtualenv\) )]($style)'

[golang]
symbol = "GO "

[rust]
symbol = "Rust "

[nodejs]
symbol = "Node "
